/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.table.DefaultTableModel;
import config.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author daniel
 */
public class Historial extends javax.swing.JFrame {

    //Variables para la conexión a la base de datos
    Conexion con = new Conexion();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    int id;
    
    public Historial() {
        initComponents();
        setLocationRelativeTo(null);
        listarRegistroMantenimiento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_registro_mantenimiento = new javax.swing.JTable();
        btn_Frame_Formularios = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bitacora");
        setBackground(new java.awt.Color(92, 184, 92));

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        tb_registro_mantenimiento.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tb_registro_mantenimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Maquina", "Nombre Motor", "Nombre Empleado", "Tipo Mantenimiento", "Fecha Mantenimiento", "Descripcion Mantenimiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_registro_mantenimiento.getTableHeader().setReorderingAllowed(false);
        tb_registro_mantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_registro_mantenimientoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb_registro_mantenimiento);
        if (tb_registro_mantenimiento.getColumnModel().getColumnCount() > 0) {
            tb_registro_mantenimiento.getColumnModel().getColumn(0).setResizable(false);
            tb_registro_mantenimiento.getColumnModel().getColumn(1).setResizable(false);
            tb_registro_mantenimiento.getColumnModel().getColumn(2).setResizable(false);
            tb_registro_mantenimiento.getColumnModel().getColumn(3).setResizable(false);
            tb_registro_mantenimiento.getColumnModel().getColumn(4).setResizable(false);
            tb_registro_mantenimiento.getColumnModel().getColumn(5).setResizable(false);
        }

        btn_Frame_Formularios.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        btn_Frame_Formularios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forms.png"))); // NOI18N
        btn_Frame_Formularios.setText("Formularios");
        btn_Frame_Formularios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Frame_Formularios.setIconTextGap(14);
        btn_Frame_Formularios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Frame_FormulariosMouseClicked(evt);
            }
        });
        btn_Frame_Formularios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Frame_FormulariosActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/alert.png"))); // NOI18N
        jButton1.setText("Alertas");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setIconTextGap(14);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        jButton2.setText("Bitacora");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.setIconTextGap(14);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Frame_Formularios)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 489, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Frame_Formularios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_registro_mantenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_registro_mantenimientoMouseClicked

    }//GEN-LAST:event_tb_registro_mantenimientoMouseClicked

    private void btn_Frame_FormulariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Frame_FormulariosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Frame_FormulariosMouseClicked

    private void btn_Frame_FormulariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Frame_FormulariosActionPerformed
        Formularios frm = new Formularios();
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_Frame_FormulariosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Mantenimiento man = new Mantenimiento();
        man.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Historial hs = new Historial();
        hs.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Historial().setVisible(true);
            }
        });
        
    }
    
    void listarRegistroMantenimiento(){
        String sql = "SELECT maquina.Nombre_Maquina, motor.Nombre_Motor, empleado.Nombre_Empleado, mantenimiento.Tipo_Mantenimiento, registro_mantenimiento.Fecha_Mantenimiento, registro_mantenimiento.Descripcion_Mantenimiento FROM registro_mantenimiento INNER JOIN motor on registro_mantenimiento.Id_Motor = motor.Id_Motor INNER JOIN empleado on registro_mantenimiento.Id_Empleado = empleado.Id_Empleado INNER JOIN mantenimiento on registro_mantenimiento.Id_Mantenimiento = mantenimiento.Id_Mantenimiento INNER JOIN maquina on motor.Id_Maquina = maquina.Id_Maquina ORDER BY registro_mantenimiento.Fecha_Mantenimiento ASC";
        try{
            cn = con.getConnection();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            Object[]persona = new Object[6];
            modelo = (DefaultTableModel)tb_registro_mantenimiento.getModel();
            while (rs.next()){
                persona[0]= rs.getString("Nombre_Maquina");
                persona[1] = rs.getString("Nombre_Motor");
                persona[2] = rs.getString("Nombre_Empleado");
                persona[3] = rs.getString("Tipo_Mantenimiento");
                persona[4] = rs.getString("Fecha_Mantenimiento");
                persona[5] = rs.getString("Descripcion_Mantenimiento");
                modelo.addRow(persona);
            }
            tb_registro_mantenimiento.setModel(modelo);
        } catch(Exception e){
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Frame_Formularios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tb_registro_mantenimiento;
    // End of variables declaration//GEN-END:variables
}
