/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import clases.clase_empleado;
import clases.clase_tipo_mantenimiento;
import config.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daniel
 */
public class Mantenimiento extends javax.swing.JFrame {

    //Variables para la conexión a la base de datos
    Conexion con = new Conexion();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    int id;
    
    public Mantenimiento() {
        initComponents();
        setLocationRelativeTo(null);
        
        listarMantenimientos();
        
        clase_empleado emp = new clase_empleado();
        emp.llenar_combo_empleado(combo_empleado);
        
        clase_tipo_mantenimiento tma = new clase_tipo_mantenimiento();
        tma.llenar_combo_tipo_mantenimiento(combo_tipo_mantenimiento);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_Mantenimientos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_Frame_Formularios = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_Id_Motor = new javax.swing.JTextField();
        combo_empleado = new javax.swing.JComboBox<>();
        combo_tipo_mantenimiento = new javax.swing.JComboBox<>();
        txt_Fecha_Mantenimiento_Realizado = new javax.swing.JTextField();
        txt_Fecha_Mantenimiento_Estimado = new javax.swing.JTextField();
        btn_Mantenimiento_Realizado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Descripcion_Mantenimiento = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mantenimientos");

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        tb_Mantenimientos.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tb_Mantenimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Ultimo", "Fecha Siguiente", "Id Motor", "Nombre Motor", "Maquina"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_Mantenimientos.getTableHeader().setReorderingAllowed(false);
        tb_Mantenimientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_MantenimientosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb_Mantenimientos);
        if (tb_Mantenimientos.getColumnModel().getColumnCount() > 0) {
            tb_Mantenimientos.getColumnModel().getColumn(0).setResizable(false);
            tb_Mantenimientos.getColumnModel().getColumn(1).setResizable(false);
            tb_Mantenimientos.getColumnModel().getColumn(2).setResizable(false);
            tb_Mantenimientos.getColumnModel().getColumn(3).setResizable(false);
            tb_Mantenimientos.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id_Motor: ");

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Empleado: ");

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo de mantenimiento: ");

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha del mantenimiento");

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha Proximo");

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Descripción");

        btn_Frame_Formularios.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        btn_Frame_Formularios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forms.png"))); // NOI18N
        btn_Frame_Formularios.setText("Formularios");
        btn_Frame_Formularios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Frame_Formularios.setIconTextGap(14);
        btn_Frame_Formularios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Frame_FormulariosMouseClicked(evt);
            }
        });
        btn_Frame_Formularios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Frame_FormulariosActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/alert.png"))); // NOI18N
        jButton1.setText("Alertas");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setIconTextGap(14);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        jButton2.setText("Bitacora");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.setIconTextGap(14);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        combo_empleado.setName(""); // NOI18N

        combo_tipo_mantenimiento.setName(""); // NOI18N

        txt_Fecha_Mantenimiento_Estimado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Fecha_Mantenimiento_EstimadoActionPerformed(evt);
            }
        });

        btn_Mantenimiento_Realizado.setBackground(new java.awt.Color(92, 184, 92));
        btn_Mantenimiento_Realizado.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        btn_Mantenimiento_Realizado.setText("Aceptar");
        btn_Mantenimiento_Realizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Mantenimiento_RealizadoActionPerformed(evt);
            }
        });

        txt_Descripcion_Mantenimiento.setColumns(20);
        txt_Descripcion_Mantenimiento.setRows(5);
        jScrollPane1.setViewportView(txt_Descripcion_Mantenimiento);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Mantenimiento_Realizado))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addGap(109, 109, 109)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_Id_Motor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combo_empleado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1)
                                    .addComponent(txt_Fecha_Mantenimiento_Estimado)
                                    .addComponent(txt_Fecha_Mantenimiento_Realizado)
                                    .addComponent(combo_tipo_mantenimiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(36, 36, 36))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Frame_Formularios)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Frame_Formularios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_Id_Motor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combo_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combo_tipo_mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Fecha_Mantenimiento_Realizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Fecha_Mantenimiento_Estimado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(btn_Mantenimiento_Realizado)
                        .addGap(0, 91, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_MantenimientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_MantenimientosMouseClicked
        int fila = tb_Mantenimientos.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(null, "Seleccione un registro");
        } else{
            String fechaRealizado = (String)tb_Mantenimientos.getValueAt(fila, 0);
            String fechaEstimada = (String)tb_Mantenimientos.getValueAt(fila, 1);
            String id = (String)tb_Mantenimientos.getValueAt(fila, 2);
            
            txt_Id_Motor.setText(""+id);
            txt_Fecha_Mantenimiento_Realizado.setText(""+fechaRealizado);
            txt_Fecha_Mantenimiento_Estimado.setText(""+fechaEstimada);
        }
    }//GEN-LAST:event_tb_MantenimientosMouseClicked

    private void txt_Fecha_Mantenimiento_EstimadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Fecha_Mantenimiento_EstimadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Fecha_Mantenimiento_EstimadoActionPerformed

    private void btn_Mantenimiento_RealizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Mantenimiento_RealizadoActionPerformed
        AgregarRegistro();
        modificarFechas();
        listarMantenimientos();
        nuevoMantenimiento();
    }//GEN-LAST:event_btn_Mantenimiento_RealizadoActionPerformed

    private void btn_Frame_FormulariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Frame_FormulariosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Frame_FormulariosMouseClicked

    private void btn_Frame_FormulariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Frame_FormulariosActionPerformed
        Formularios frm = new Formularios();
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_Frame_FormulariosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Mantenimiento man = new Mantenimiento();
        man.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Historial hs = new Historial();
        hs.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mantenimiento().setVisible(true);
            }
        });
    }
    
    void listarMantenimientos(){
        String sql = "SELECT motor.Fecha_Inicio_Motor, motor.Fecha_Fin_Motor, motor.Id_Motor, motor.Nombre_Motor, maquina.Nombre_Maquina FROM motor INNER JOIN maquina on motor.Id_Maquina = maquina.Id_Maquina ORDER BY motor.Fecha_Fin_Motor ASC";
        try{
            cn = con.getConnection();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            Object[]persona = new Object[5];
            modelo = (DefaultTableModel)tb_Mantenimientos.getModel();
            while (rs.next()){
                persona[0]= rs.getString("Fecha_Inicio_Motor");
                persona[1] = rs.getString("Fecha_Fin_Motor");
                persona[2] = rs.getString("Id_Motor");
                persona[3] = rs.getString("Nombre_Motor");
                persona[4] = rs.getString("Nombre_Maquina");
                modelo.addRow(persona);
            }
            tb_Mantenimientos.setModel(modelo);
        } catch(Exception e){
        }
    }
    
    void modificarFechas(){
        String id = txt_Id_Motor.getText();
        String fechaRealizado = txt_Fecha_Mantenimiento_Realizado.getText();
        String fechaEstimada = txt_Fecha_Mantenimiento_Estimado.getText();
        String sql = "update motor set Id_Motor = '"+id+"',Fecha_Inicio_Motor = '"+fechaRealizado+"',Fecha_Fin_Motor = '"+fechaEstimada+"' where Id_Motor = "+id;
        if(id.equals("")||fechaRealizado.equals("")||fechaEstimada.equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar fechas");
        }else{
            try{
                cn = con.getConnection();
                st = cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Mantenimiento Realizado");
                limpiarTablaMantenimientos();
            }catch(Exception e){
            }
        }    
    }
    
    void limpiarTablaMantenimientos(){
        for(int i = 0; i<=tb_Mantenimientos.getRowCount();i++){
            modelo.removeRow(i);
            i = i-1;
        }
    }
    
    void nuevoMantenimiento(){
        txt_Id_Motor.setText("");
        txt_Fecha_Mantenimiento_Realizado.setText("");
        txt_Fecha_Mantenimiento_Estimado.setText("");
        txt_Descripcion_Mantenimiento.setText("");
        txt_Id_Motor.requestFocus();
    }
    
    void AgregarRegistro(){
        String id = txt_Id_Motor.getText();
        String empleado = combo_empleado.getItemAt(combo_empleado.getSelectedIndex()).getCodigo();
        String mantenimiento = combo_tipo_mantenimiento.getItemAt(combo_tipo_mantenimiento.getSelectedIndex()).getCodigo();
        String fechaRealizado = txt_Fecha_Mantenimiento_Realizado.getText();
        //String fechaEstimada = txt_Fecha_Mantenimiento_Estimado.getText();
        String descripcion = txt_Descripcion_Mantenimiento.getText();
        if(id.equals("")||empleado.equals("")||mantenimiento.equals("")||fechaRealizado.equals("")||descripcion.equals("")){
            JOptionPane.showMessageDialog(null, "Debe llenar el formulario");
        } else{
            String sql = "insert into registro_mantenimiento(Id_Motor, Id_Empleado, Id_Mantenimiento, Fecha_Mantenimiento, Descripcion_Mantenimiento)values('"+id+"','"+empleado+"','"+mantenimiento+"','"+fechaRealizado+"','"+descripcion+"')";
            try{
                cn = con.getConnection();
                st = cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Mantenimiento Realizado");
                limpiarTablaMantenimientos();
            }catch(Exception e){      
            } 
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Frame_Formularios;
    private javax.swing.JButton btn_Mantenimiento_Realizado;
    private javax.swing.JComboBox<clase_empleado> combo_empleado;
    private javax.swing.JComboBox<clase_tipo_mantenimiento> combo_tipo_mantenimiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tb_Mantenimientos;
    private javax.swing.JTextArea txt_Descripcion_Mantenimiento;
    private javax.swing.JTextField txt_Fecha_Mantenimiento_Estimado;
    private javax.swing.JTextField txt_Fecha_Mantenimiento_Realizado;
    private javax.swing.JTextField txt_Id_Motor;
    // End of variables declaration//GEN-END:variables
}
