package vista;

import config.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TablaCargo extends javax.swing.JFrame {

    //Variables para la conexión a la base de datos
    Conexion con = new Conexion();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    int id;
    
    public TablaCargo() {
        initComponents();
        setLocationRelativeTo(null);
        listarCargo();
        listarDepartamento();
        listarMaquina();
        listarTipoMantenimiento();
        listarMotor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_Id_Maquina = new javax.swing.JTextField();
        txt_Nombre_Maquina = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_Serial_Maquina = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_Maquina = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        btn_Agregar_Maquina = new javax.swing.JButton();
        btn_Eliminar_Maquina = new javax.swing.JButton();
        btn_Modificar_Maquina = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tb_Motor = new javax.swing.JTable();
        jPanel20 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_Id_Motor = new javax.swing.JTextField();
        txt_Nombre_Motor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_Fecha_Inicio_Motor = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_Fecha_Fin_Motor = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_Estado_Motor = new javax.swing.JTextField();
        txt_Id_Maquina_Motor = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        btn_Agregar_Motor = new javax.swing.JButton();
        btn_Eliminar_Motor = new javax.swing.JButton();
        btn_Modificar_Motor = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_Id_Cargo = new javax.swing.JTextField();
        txt_Nombre_Cargo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Cargo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_Agregar_Cargo = new javax.swing.JButton();
        btn_Eliminar_Cargo = new javax.swing.JButton();
        btn_Modificar_Cargo = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_Departamento = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_Id_Departamento = new javax.swing.JTextField();
        txt_Nombre_Departamento = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        btn_Agregar_Departamento = new javax.swing.JButton();
        btn_Eliminar_Departamento = new javax.swing.JButton();
        btn_Modificar_Departamento = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_Id_Tipo_Mantenimiento = new javax.swing.JTextField();
        txt_Nombre_Tipo_Mantenimiento = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb_Tipo_Mantenimiento = new javax.swing.JTable();
        jPanel18 = new javax.swing.JPanel();
        btn_Agregar_Tipo_Mantenimiento = new javax.swing.JButton();
        btn_Eliminar_Tipo_Mantenimiento = new javax.swing.JButton();
        btn_Modificar_Tipo_Mantenimiento = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("TABLA MAQUINA");

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel8.setText("ID: ");

        jLabel9.setText("Nombre: ");

        txt_Id_Maquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Id_MaquinaActionPerformed(evt);
            }
        });

        jLabel10.setText("Serial: ");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Serial_Maquina, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(txt_Id_Maquina, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(txt_Nombre_Maquina))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_Id_Maquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_Nombre_Maquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_Serial_Maquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista"));

        tb_Maquina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Serial"
            }
        ));
        tb_Maquina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_MaquinaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb_Maquina);
        if (tb_Maquina.getColumnModel().getColumnCount() > 0) {
            tb_Maquina.getColumnModel().getColumn(0).setMinWidth(75);
            tb_Maquina.getColumnModel().getColumn(0).setPreferredWidth(50);
            tb_Maquina.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Operación"));

        btn_Agregar_Maquina.setText("Agregar");
        btn_Agregar_Maquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Agregar_MaquinaActionPerformed(evt);
            }
        });

        btn_Eliminar_Maquina.setText("Eliminar");
        btn_Eliminar_Maquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Eliminar_MaquinaActionPerformed(evt);
            }
        });

        btn_Modificar_Maquina.setText("Modificar");
        btn_Modificar_Maquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Modificar_MaquinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(btn_Agregar_Maquina)
                .addGap(20, 20, 20)
                .addComponent(btn_Modificar_Maquina)
                .addGap(18, 18, 18)
                .addComponent(btn_Eliminar_Maquina)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Agregar_Maquina)
                    .addComponent(btn_Modificar_Maquina)
                    .addComponent(btn_Eliminar_Maquina))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Maquina", jPanel4);

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista"));

        tb_Motor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "ID maquina", "Maquina"
            }
        ));
        tb_Motor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_MotorMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tb_Motor);
        if (tb_Motor.getColumnModel().getColumnCount() > 0) {
            tb_Motor.getColumnModel().getColumn(0).setMinWidth(75);
            tb_Motor.getColumnModel().getColumn(0).setPreferredWidth(50);
            tb_Motor.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
        );

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel14.setText("ID: ");

        jLabel15.setText("Nombre: ");

        txt_Id_Motor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Id_MotorActionPerformed(evt);
            }
        });

        jLabel16.setText("Fecha Inicio: ");

        jLabel17.setText("Fecha Fin: ");

        jLabel18.setText("Estado: ");

        jLabel19.setText("Id Maquina: ");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(56, 56, 56)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Id_Motor, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(txt_Nombre_Motor)))
                    .addComponent(jLabel15)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Fecha_Inicio_Motor, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(txt_Fecha_Fin_Motor)
                            .addComponent(txt_Id_Maquina_Motor)
                            .addComponent(txt_Estado_Motor))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_Id_Motor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_Nombre_Motor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_Fecha_Inicio_Motor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_Fecha_Fin_Motor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt_Estado_Motor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txt_Id_Maquina_Motor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder("Operación"));

        btn_Agregar_Motor.setText("Agregar");
        btn_Agregar_Motor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Agregar_MotorActionPerformed(evt);
            }
        });

        btn_Eliminar_Motor.setText("Eliminar");
        btn_Eliminar_Motor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Eliminar_MotorActionPerformed(evt);
            }
        });

        btn_Modificar_Motor.setText("Modificar");
        btn_Modificar_Motor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Modificar_MotorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addComponent(btn_Agregar_Motor)
                .addGap(20, 20, 20)
                .addComponent(btn_Modificar_Motor)
                .addGap(18, 18, 18)
                .addComponent(btn_Eliminar_Motor)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Agregar_Motor)
                    .addComponent(btn_Modificar_Motor)
                    .addComponent(btn_Eliminar_Motor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26))))
        );

        jTabbedPane1.addTab("Motor", jPanel5);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel2.setText("ID: ");

        jLabel3.setText("Nombre: ");

        txt_Id_Cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Id_CargoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Id_Cargo, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(txt_Nombre_Cargo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Id_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Nombre_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista"));

        tb_Cargo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ));
        tb_Cargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_CargoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Cargo);
        if (tb_Cargo.getColumnModel().getColumnCount() > 0) {
            tb_Cargo.getColumnModel().getColumn(0).setMinWidth(100);
            tb_Cargo.getColumnModel().getColumn(0).setPreferredWidth(50);
            tb_Cargo.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("TABLA CARGO");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Operación"));

        btn_Agregar_Cargo.setText("Agregar");
        btn_Agregar_Cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Agregar_CargoActionPerformed(evt);
            }
        });

        btn_Eliminar_Cargo.setText("Eliminar");
        btn_Eliminar_Cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Eliminar_CargoActionPerformed(evt);
            }
        });

        btn_Modificar_Cargo.setText("Modificar");
        btn_Modificar_Cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Modificar_CargoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btn_Agregar_Cargo)
                .addGap(20, 20, 20)
                .addComponent(btn_Modificar_Cargo)
                .addGap(18, 18, 18)
                .addComponent(btn_Eliminar_Cargo)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Agregar_Cargo)
                    .addComponent(btn_Modificar_Cargo)
                    .addComponent(btn_Eliminar_Cargo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 130, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cargo", jPanel6);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista"));

        tb_Departamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ));
        tb_Departamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_DepartamentoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_Departamento);
        if (tb_Departamento.getColumnModel().getColumnCount() > 0) {
            tb_Departamento.getColumnModel().getColumn(0).setMinWidth(100);
            tb_Departamento.getColumnModel().getColumn(0).setPreferredWidth(50);
            tb_Departamento.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("TABLA DEPARTAMENTO");

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel5.setText("ID: ");

        jLabel6.setText("Nombre: ");

        txt_Id_Departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Id_DepartamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Id_Departamento, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(txt_Nombre_Departamento))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Id_Departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_Nombre_Departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Operación"));

        btn_Agregar_Departamento.setText("Agregar");
        btn_Agregar_Departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Agregar_DepartamentoActionPerformed(evt);
            }
        });

        btn_Eliminar_Departamento.setText("Eliminar");
        btn_Eliminar_Departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Eliminar_DepartamentoActionPerformed(evt);
            }
        });

        btn_Modificar_Departamento.setText("Modificar");
        btn_Modificar_Departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Modificar_DepartamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(btn_Agregar_Departamento)
                .addGap(20, 20, 20)
                .addComponent(btn_Modificar_Departamento)
                .addGap(18, 18, 18)
                .addComponent(btn_Eliminar_Departamento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Agregar_Departamento)
                    .addComponent(btn_Modificar_Departamento)
                    .addComponent(btn_Eliminar_Departamento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Departamento", jPanel7);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("TABLA TIPOS DE MANTENIMIENTO");

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel12.setText("ID: ");

        jLabel13.setText("Nombre: ");

        txt_Id_Tipo_Mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Id_Tipo_MantenimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Id_Tipo_Mantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(txt_Nombre_Tipo_Mantenimiento))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_Id_Tipo_Mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_Nombre_Tipo_Mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista"));

        tb_Tipo_Mantenimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ));
        tb_Tipo_Mantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_Tipo_MantenimientoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tb_Tipo_Mantenimiento);
        if (tb_Tipo_Mantenimiento.getColumnModel().getColumnCount() > 0) {
            tb_Tipo_Mantenimiento.getColumnModel().getColumn(0).setMinWidth(100);
            tb_Tipo_Mantenimiento.getColumnModel().getColumn(0).setPreferredWidth(50);
            tb_Tipo_Mantenimiento.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Operación"));

        btn_Agregar_Tipo_Mantenimiento.setText("Agregar");
        btn_Agregar_Tipo_Mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Agregar_Tipo_MantenimientoActionPerformed(evt);
            }
        });

        btn_Eliminar_Tipo_Mantenimiento.setText("Eliminar");
        btn_Eliminar_Tipo_Mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Eliminar_Tipo_MantenimientoActionPerformed(evt);
            }
        });

        btn_Modificar_Tipo_Mantenimiento.setText("Modificar");
        btn_Modificar_Tipo_Mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Modificar_Tipo_MantenimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(btn_Agregar_Tipo_Mantenimiento)
                .addGap(20, 20, 20)
                .addComponent(btn_Modificar_Tipo_Mantenimiento)
                .addGap(18, 18, 18)
                .addComponent(btn_Eliminar_Tipo_Mantenimiento)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Agregar_Tipo_Mantenimiento)
                    .addComponent(btn_Modificar_Tipo_Mantenimiento)
                    .addComponent(btn_Eliminar_Tipo_Mantenimiento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Tipo de Mantenimiento", jPanel14);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Empleado", jPanel15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Id_CargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Id_CargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Id_CargoActionPerformed

    private void btn_Agregar_CargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Agregar_CargoActionPerformed
        //Agregamos el método agregar a la acción de botón
        Agregar();
        listarCargo();
        nuevo();
    }//GEN-LAST:event_btn_Agregar_CargoActionPerformed

    private void tb_CargoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_CargoMouseClicked
        int fila = tb_Cargo.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(null, "Usuario no selecccionado");
        } else{
            String id = (String)tb_Cargo.getValueAt(fila, 0);
            String nombre = (String)tb_Cargo.getValueAt(fila, 1);
            
            txt_Id_Cargo.setText(""+id);
            txt_Nombre_Cargo.setText(""+nombre);
        }
    }//GEN-LAST:event_tb_CargoMouseClicked

    private void btn_Modificar_CargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Modificar_CargoActionPerformed
        modificar();
        listarCargo();
        nuevo();
    }//GEN-LAST:event_btn_Modificar_CargoActionPerformed

    private void btn_Eliminar_CargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Eliminar_CargoActionPerformed
        eliminar();
        listarCargo();
        nuevo();
    }//GEN-LAST:event_btn_Eliminar_CargoActionPerformed

    private void tb_DepartamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_DepartamentoMouseClicked
        int fila = tb_Departamento.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(null, "Usuario no selecccionado");
        } else{
            String id = (String)tb_Departamento.getValueAt(fila, 0);
            String nombre = (String)tb_Departamento.getValueAt(fila, 1);
            
            txt_Id_Departamento.setText(""+id);
            txt_Nombre_Departamento.setText(""+nombre);
        }
    }//GEN-LAST:event_tb_DepartamentoMouseClicked

    private void txt_Id_DepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Id_DepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Id_DepartamentoActionPerformed

    private void btn_Agregar_DepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Agregar_DepartamentoActionPerformed
        AgregarDepartamento();
        listarDepartamento();
        nuevoDepartamento();
    }//GEN-LAST:event_btn_Agregar_DepartamentoActionPerformed

    private void btn_Eliminar_DepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Eliminar_DepartamentoActionPerformed
        eliminarDepartamento();
        listarDepartamento();
        nuevoDepartamento();
    }//GEN-LAST:event_btn_Eliminar_DepartamentoActionPerformed

    private void btn_Modificar_DepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Modificar_DepartamentoActionPerformed
        modificarDepartamento();
        listarDepartamento();
        nuevoDepartamento();
    }//GEN-LAST:event_btn_Modificar_DepartamentoActionPerformed

    private void txt_Id_MaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Id_MaquinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Id_MaquinaActionPerformed

    private void tb_MaquinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_MaquinaMouseClicked
        int fila = tb_Maquina.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(null, "Usuario no selecccionado");
        } else{
            String id = (String)tb_Maquina.getValueAt(fila, 0);
            String nombre = (String)tb_Maquina.getValueAt(fila, 1);
            String serial = (String)tb_Maquina.getValueAt(fila, 2);
            
            txt_Id_Maquina.setText(""+id);
            txt_Nombre_Maquina.setText(""+nombre);
            txt_Serial_Maquina.setText(""+serial);
        }
    }//GEN-LAST:event_tb_MaquinaMouseClicked

    private void btn_Agregar_MaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Agregar_MaquinaActionPerformed
        AgregarMaquina();
        listarMaquina();
        nuevoMaquina();
    }//GEN-LAST:event_btn_Agregar_MaquinaActionPerformed

    private void btn_Eliminar_MaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Eliminar_MaquinaActionPerformed
        eliminarMaquina();
        listarMaquina();
        nuevoMaquina();
    }//GEN-LAST:event_btn_Eliminar_MaquinaActionPerformed

    private void btn_Modificar_MaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Modificar_MaquinaActionPerformed
        modificarMaquina();
        listarMaquina();
        nuevoMaquina();
    }//GEN-LAST:event_btn_Modificar_MaquinaActionPerformed

    private void txt_Id_Tipo_MantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Id_Tipo_MantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Id_Tipo_MantenimientoActionPerformed

    private void tb_Tipo_MantenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_Tipo_MantenimientoMouseClicked
        int fila = tb_Tipo_Mantenimiento.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(null, "Usuario no selecccionado");
        } else{
            String id = (String)tb_Tipo_Mantenimiento.getValueAt(fila, 0);
            String nombre = (String)tb_Tipo_Mantenimiento.getValueAt(fila, 1);
            
            txt_Id_Tipo_Mantenimiento.setText(""+id);
            txt_Nombre_Tipo_Mantenimiento.setText(""+nombre);
        }
    }//GEN-LAST:event_tb_Tipo_MantenimientoMouseClicked

    private void btn_Agregar_Tipo_MantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Agregar_Tipo_MantenimientoActionPerformed
        AgregarTipoMantenimiento();
        listarTipoMantenimiento();
        nuevoTipoMantenimiento();
    }//GEN-LAST:event_btn_Agregar_Tipo_MantenimientoActionPerformed

    private void btn_Eliminar_Tipo_MantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Eliminar_Tipo_MantenimientoActionPerformed
        eliminarTipoMantenimiento();
        listarTipoMantenimiento();
        nuevoTipoMantenimiento();
    }//GEN-LAST:event_btn_Eliminar_Tipo_MantenimientoActionPerformed

    private void btn_Modificar_Tipo_MantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Modificar_Tipo_MantenimientoActionPerformed
        modificarTipoMantenimiento();
        listarTipoMantenimiento();
        nuevoTipoMantenimiento();
    }//GEN-LAST:event_btn_Modificar_Tipo_MantenimientoActionPerformed

    private void tb_MotorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_MotorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_MotorMouseClicked

    private void txt_Id_MotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Id_MotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Id_MotorActionPerformed

    private void btn_Agregar_MotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Agregar_MotorActionPerformed
        AgregarMotor();
        listarMotor();
        nuevoMotor();
    }//GEN-LAST:event_btn_Agregar_MotorActionPerformed

    private void btn_Eliminar_MotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Eliminar_MotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Eliminar_MotorActionPerformed

    private void btn_Modificar_MotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Modificar_MotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Modificar_MotorActionPerformed

    void modificar(){
        String id = txt_Id_Cargo.getText();
        String nombre = txt_Nombre_Cargo.getText();
        String sql = "update cargo set Id_Cargo = '"+id+"',Nombre_Cargo = '"+nombre+"' where Id_Cargo = "+id;
        if(id.equals("")||nombre.equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar datos");
        }else{
            try{
                cn = con.getConnection();
                st = cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Usuario Actualizado");
                limpiartabla();
            }catch(Exception e){
            }
        }    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaCargo().setVisible(true);
            }
        });
    }
    
    //Creación de un Método
    void listarCargo(){
        String sql = "select * from cargo";
        try{
            cn = con.getConnection();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            Object[]persona = new Object[2];
            modelo = (DefaultTableModel)tb_Cargo.getModel();
            while (rs.next()){
                persona[0]= rs.getString("Id_Cargo");
                persona[1] = rs.getString("Nombre_Cargo");
                modelo.addRow(persona);
            }
            tb_Cargo.setModel(modelo);
        } catch(Exception e){
        }
    }
    
    void Agregar(){
        String id = txt_Id_Cargo.getText();
        String nombre = txt_Nombre_Cargo.getText();
        if(id.equals("")||nombre.equals("")){
            JOptionPane.showMessageDialog(null, "Cajas vacias");
        } else{
            String sql = "insert into cargo(Id_Cargo, Nombre_Cargo)values('"+id+"','"+nombre+"')";
            try{
                cn = con.getConnection();
                st = cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Usuario Agregado");
                limpiartabla();
            }catch(Exception e){      
            } 
        }
    }
    
    void limpiartabla(){
        for(int i = 0; i<=tb_Cargo.getRowCount();i++){
            modelo.removeRow(i);
            i = i-1;
        }
    }
    
    void eliminar(){
        String id = txt_Id_Cargo.getText();
        int filaseleccionado = tb_Cargo.getSelectedRow();
        if(filaseleccionado==-1){
            JOptionPane.showMessageDialog(null, "Debe seleccionar Fila");
        } else{
            String sql = "delete from cargo where Id_Cargo="+id;
            try{
                cn = con.getConnection();
                st = cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Usuario Eliminado con éxito");
                limpiartabla();
            }catch(Exception e){            
            }
        }
    }
    
    void nuevo(){
        txt_Id_Cargo.setText("");
        txt_Nombre_Cargo.setText("");
        txt_Id_Cargo.requestFocus();
    }
    
    //Creación de un Método
    void listarDepartamento(){
        String sql = "select * from departamento";
        try{
            cn = con.getConnection();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            Object[]persona = new Object[2];
            modelo = (DefaultTableModel)tb_Departamento.getModel();
            while (rs.next()){
                persona[0]= rs.getString("Id_Departamento");
                persona[1] = rs.getString("Nombre_Departamento");
                modelo.addRow(persona);
            }
            tb_Departamento.setModel(modelo);
        } catch(Exception e){
        }
    }
    
    void AgregarDepartamento(){
        String id = txt_Id_Departamento.getText();
        String nombre = txt_Nombre_Departamento.getText();
        if(id.equals("")||nombre.equals("")){
            JOptionPane.showMessageDialog(null, "Cajas vacias");
        } else{
            String sql = "insert into departamento(Id_Departamento, Nombre_Departamento)values('"+id+"','"+nombre+"')";
            try{
                cn = con.getConnection();
                st = cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Usuario Agregado");
                limpiartablaDepartamento();
            }catch(Exception e){
            } 
        }
    }
    
    void modificarDepartamento(){
        String id = txt_Id_Departamento.getText();
        String nombre = txt_Nombre_Departamento.getText();
        String sql = "update departamento set Id_Departamento = '"+id+"',Nombre_Departamento = '"+nombre+"' where Id_Departamento = "+id;
        if(id.equals("")||nombre.equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar datos");
        }else{
            try{
                cn = con.getConnection();
                st = cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Usuario Actualizado");
                limpiartablaDepartamento();
            }catch(Exception e){
            }
        }    
    }
    
    void eliminarDepartamento(){
        String id = txt_Id_Departamento.getText();
        int filaseleccionado = tb_Departamento.getSelectedRow();
        if(filaseleccionado==-1){
            JOptionPane.showMessageDialog(null, "Debe seleccionar Fila");
        } else{
            String sql = "delete from departamento where Id_Departamento="+id;
            try{
                cn = con.getConnection();
                st = cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Usuario Eliminado con éxito");
                limpiartablaDepartamento();
            }catch(Exception e){
            
            }
        }
    }
    
    void limpiartablaDepartamento(){
        for(int i = 0; i<=tb_Departamento.getRowCount();i++){
            modelo.removeRow(i);
            i = i-1;
        }
    }
    
    void nuevoDepartamento(){
        txt_Id_Departamento.setText("");
        txt_Nombre_Departamento.setText("");
        txt_Id_Departamento.requestFocus();
    }
    
    //Creación de un Método
    void listarMaquina(){
        String sql = "select * from maquina";
        try{
            cn = con.getConnection();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            Object[]persona = new Object[3];
            modelo = (DefaultTableModel)tb_Maquina.getModel();
            while (rs.next()){
                persona[0]= rs.getString("Id_Maquina");
                persona[1] = rs.getString("Nombre_Maquina");
                persona[2] = rs.getString("Serial_Maquina");
                modelo.addRow(persona);
            }
            tb_Maquina.setModel(modelo);
        } catch(Exception e){
        }
    }
    
    void AgregarMaquina(){
        String id = txt_Id_Maquina.getText();
        String nombre = txt_Nombre_Maquina.getText();
        String serial = txt_Serial_Maquina.getText();
        if(id.equals("")||nombre.equals("")||serial.equals("")){
            JOptionPane.showMessageDialog(null, "Cajas vacias");
        } else{
            String sql = "insert into maquina(Id_Maquina, Nombre_Maquina, Serial_Maquina)values('"+id+"','"+nombre+"','"+serial+"')";
            try{
                cn = con.getConnection();
                st = cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Máquina agregada");
                limpiartablaMaquina();
            }catch(Exception e){      
            } 
        }
    }
    
    void modificarMaquina(){
        String id = txt_Id_Maquina.getText();
        String nombre = txt_Nombre_Maquina.getText();
        String serial = txt_Serial_Maquina.getText();
        String sql = "update maquina set Id_Maquina = '"+id+"',Nombre_Maquina = '"+nombre+"', Serial_Maquina = '"+serial+"' where Id_Maquina = "+id;
        if(id.equals("")||nombre.equals("")||serial.equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar datos");
        }else{
            try{
                cn = con.getConnection();
                st = cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Maquina Actualizada");
                limpiartablaMaquina();
            }catch(Exception e){
            }
        }    
    }
    
    void eliminarMaquina(){
        String id = txt_Id_Maquina.getText();
        int filaseleccionado = tb_Maquina.getSelectedRow();
        if(filaseleccionado==-1){
            JOptionPane.showMessageDialog(null, "Debe seleccionar Fila");
        } else{
            String sql = "delete from maquina where Id_Maquina="+id;
            try{
                cn = con.getConnection();
                st = cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Usuario Eliminado con éxito");
                limpiartablaMaquina();
            }catch(Exception e){            
            }
        }
    }
    
    void nuevoMaquina(){
        txt_Id_Maquina.setText("");
        txt_Nombre_Maquina.setText("");
        txt_Serial_Maquina.setText("");
        txt_Id_Maquina.requestFocus();
    }
    
    void limpiartablaMaquina(){
        for(int i = 0; i<=tb_Maquina.getRowCount();i++){
            modelo.removeRow(i);
            i = i-1;
        }
    }
    
    void listarTipoMantenimiento(){
        String sql = "select * from mantenimiento";
        try{
            cn = con.getConnection();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            Object[]persona = new Object[2];
            modelo = (DefaultTableModel)tb_Tipo_Mantenimiento.getModel();
            while (rs.next()){
                persona[0]= rs.getString("Id_Mantenimiento");
                persona[1] = rs.getString("Tipo_Mantenimiento");
                modelo.addRow(persona);
            }
            tb_Tipo_Mantenimiento.setModel(modelo);
        } catch(Exception e){
        }
    }
    
    void AgregarTipoMantenimiento(){
        String id = txt_Id_Tipo_Mantenimiento.getText();
        String nombre = txt_Nombre_Tipo_Mantenimiento.getText();
        if(id.equals("")||nombre.equals("")){
            JOptionPane.showMessageDialog(null, "Cajas vacias");
        } else{
            String sql = "insert into mantenimiento(Id_Mantenimiento, Tipo_Mantenimiento)values('"+id+"','"+nombre+"')";
            try{
                cn = con.getConnection();
                st = cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Tipo de Mantenimiento Agregado");
                limpiartablaTipoMantenimiento();
            }catch(Exception e){      
            } 
        }
    }
    
    void modificarTipoMantenimiento(){
        String id = txt_Id_Maquina.getText();
        String nombre = txt_Nombre_Maquina.getText();
        String sql = "update mantenimiento set Id_Mantenimiento = '"+id+"',Tipo_Mantenimiento = '"+nombre+"' where Id_Mantenimiento = "+id;
        if(id.equals("")||nombre.equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar datos");
        }else{
            try{
                cn = con.getConnection();
                st = cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Tipo de mantenimiento actualizado");
                limpiartablaTipoMantenimiento();
            }catch(Exception e){
            }
        }    
    }
    
    void eliminarTipoMantenimiento(){
        String id = txt_Id_Tipo_Mantenimiento.getText();
        int filaseleccionado = tb_Tipo_Mantenimiento.getSelectedRow();
        if(filaseleccionado==-1){
            JOptionPane.showMessageDialog(null, "Debe seleccionar Fila");
        } else{
            String sql = "delete from mantenimiento where Id_Mantenimiento="+id;
            try{
                cn = con.getConnection();
                st = cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Tipo de Mantenimiento eliminado Exitosamente");
                limpiartablaTipoMantenimiento();
            }catch(Exception e){            
            }
        }
    }
    
    void nuevoTipoMantenimiento(){
        txt_Id_Tipo_Mantenimiento.setText("");
        txt_Nombre_Tipo_Mantenimiento.setText("");
        txt_Id_Tipo_Mantenimiento.requestFocus();
    }
    
    void limpiartablaTipoMantenimiento(){
        for(int i = 0; i<=tb_Tipo_Mantenimiento.getRowCount();i++){
            modelo.removeRow(i);
            i = i-1;
        }
    }
    
        void listarMotor(){
        String sql = "SELECT motor.Id_Motor, motor.Nombre_Motor, motor.Id_Maquina, maquina.Nombre_Maquina from motor INNER JOIN maquina on motor.Id_Maquina = maquina.Id_Maquina";
        try{
            cn = con.getConnection();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            Object[]persona = new Object[4];
            modelo = (DefaultTableModel)tb_Motor.getModel();
            while (rs.next()){
                persona[0]= rs.getString("Id_Motor");
                persona[1] = rs.getString("Nombre_Motor");
                persona[2] = rs.getString("Id_Maquina");
                persona[3] = rs.getString("Nombre_Maquina");
                modelo.addRow(persona);
            }
            tb_Motor.setModel(modelo);
        } catch(Exception e){
        }
    }
        
    void AgregarMotor(){
        String id = txt_Id_Motor.getText();
        String nombre = txt_Nombre_Motor.getText();
        String fechaI = txt_Fecha_Inicio_Motor.getText();
        String fechaF = txt_Fecha_Fin_Motor.getText();
        String estado = txt_Estado_Motor.getText();
        String idMaquina = txt_Id_Maquina_Motor.getText();
        if(id.equals("")||nombre.equals("")||fechaI.equals("")||fechaF.equals("")||estado.equals("")||idMaquina.equals("")){
            JOptionPane.showMessageDialog(null, "Cajas vacias");
        } else{
            String sql = "insert into motor(Id_Motor, Nombre_Motor, Fecha_Inicio_Motor, Fecha_Fin_Motor, Estado_Motor, Id_Maquina)values('"+id+"','"+nombre+"','"+fechaI+"','"+fechaF+"','"+estado+"','"+idMaquina+"')";
            try{
                cn = con.getConnection();
                st = cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Motor agregado");
                limpiartablaMotor();
            }catch(Exception e){      
            } 
        }
    }
    
    void nuevoMotor(){
        txt_Id_Motor.setText("");
        txt_Nombre_Motor.setText("");
        txt_Fecha_Inicio_Motor.setText("");
        txt_Fecha_Fin_Motor.setText("");
        txt_Estado_Motor.setText("");
        txt_Id_Maquina_Motor.setText("");
        txt_Id_Motor.requestFocus();
    }
    
    void limpiartablaMotor(){
        for(int i = 0; i<=tb_Motor.getRowCount();i++){
            modelo.removeRow(i);
            i = i-1;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Agregar_Cargo;
    private javax.swing.JButton btn_Agregar_Departamento;
    private javax.swing.JButton btn_Agregar_Maquina;
    private javax.swing.JButton btn_Agregar_Motor;
    private javax.swing.JButton btn_Agregar_Tipo_Mantenimiento;
    private javax.swing.JButton btn_Eliminar_Cargo;
    private javax.swing.JButton btn_Eliminar_Departamento;
    private javax.swing.JButton btn_Eliminar_Maquina;
    private javax.swing.JButton btn_Eliminar_Motor;
    private javax.swing.JButton btn_Eliminar_Tipo_Mantenimiento;
    private javax.swing.JButton btn_Modificar_Cargo;
    private javax.swing.JButton btn_Modificar_Departamento;
    private javax.swing.JButton btn_Modificar_Maquina;
    private javax.swing.JButton btn_Modificar_Motor;
    private javax.swing.JButton btn_Modificar_Tipo_Mantenimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tb_Cargo;
    private javax.swing.JTable tb_Departamento;
    private javax.swing.JTable tb_Maquina;
    private javax.swing.JTable tb_Motor;
    private javax.swing.JTable tb_Tipo_Mantenimiento;
    private javax.swing.JTextField txt_Estado_Motor;
    private javax.swing.JTextField txt_Fecha_Fin_Motor;
    private javax.swing.JTextField txt_Fecha_Inicio_Motor;
    private javax.swing.JTextField txt_Id_Cargo;
    private javax.swing.JTextField txt_Id_Departamento;
    private javax.swing.JTextField txt_Id_Maquina;
    private javax.swing.JTextField txt_Id_Maquina_Motor;
    private javax.swing.JTextField txt_Id_Motor;
    private javax.swing.JTextField txt_Id_Tipo_Mantenimiento;
    private javax.swing.JTextField txt_Nombre_Cargo;
    private javax.swing.JTextField txt_Nombre_Departamento;
    private javax.swing.JTextField txt_Nombre_Maquina;
    private javax.swing.JTextField txt_Nombre_Motor;
    private javax.swing.JTextField txt_Nombre_Tipo_Mantenimiento;
    private javax.swing.JTextField txt_Serial_Maquina;
    // End of variables declaration//GEN-END:variables
}
